version: "3.8"
services:
  Service1:
    build:
      context: /home/student/MentoredProject/Service1/
      dockerfile: dockerfile
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  Service2:
    build:
      context: /home/student/MentoredProject/Service2/
      dockerfile: dockerfile
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  Service3:
    build:
      context: /home/student/MentoredProject/Service3/
      dockerfile: dockerfile
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  Service4:
    build:
      context: /home/student/MentoredProject/Service4/
      dockerfile: dockerfile
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
